#!/usr/bin/env python
"""Inject correct bot tokens from VPS token file into each Hermes profile.

Usage:
    python inject-bot-tokens.py <token-file>

The token file format is one SPACEBAR_BOT_<NAME>=<jwt> per line, as generated by
/opt/spacebar/gen-vps-tokens.js on the VPS.

This script:
1. Parses all tokens from the file
2. Writes each token to the matching profile's .env (DISCORD_BOT_TOKEN) and .env.spacebar (export SPACEBAR_BOT_TOKEN)
3. Verifies that all profiles have unique tokens after injection
"""
import os, re, sys

TOKEN_FILE = sys.argv[1] if len(sys.argv) > 1 else '${USER_HOME}/vps-tokens.env'
PROFILES_DIR = os.path.expanduser('~/AppData/Local/hermes/profiles')

if not os.path.exists(TOKEN_FILE):
    print(f"ERROR: {TOKEN_FILE} not found. Download from VPS first:")
    print("  ssh -i ~/.ssh/oracle_vps ubuntu@129.153.156.190 'cat /opt/spacebar/vps-bot-tokens.env' > ${USER_HOME}/vps-tokens.env")
    sys.exit(1)

# Parse token file
token_map = {}
with open(TOKEN_FILE) as f:
    for line in f:
        line = line.strip()
        if line.startswith('#') or not line:
            continue
        if '=' in line:
            var, token = line.split('=', 1)
            var = var.strip()
            if var.startswith('SPACEBAR_BOT_'):
                name = var.replace('SPACEBAR_BOT_', '').lower().replace('_', '-')
                token_map[name] = token.strip()

print(f"Parsed {len(token_map)} tokens from {TOKEN_FILE}")

# Write each token to the correct profile
fixed = 0
missing = []
for name, token in token_map.items():
    env_file = os.path.join(PROFILES_DIR, name, '.env')
    spacebar_file = os.path.join(PROFILES_DIR, name, '.env.spacebar')

    if os.path.exists(env_file):
        with open(env_file, 'r') as f:
            content = f.read()
        content = re.sub(
            r'^DISCORD_BOT_TOKEN\s*=\s*\S+.*$',
            f'DISCORD_BOT_TOKEN={token}',
            content,
            flags=re.MULTILINE
        )
        with open(env_file, 'w') as f:
            f.write(content)
        fixed += 1
    else:
        missing.append(name)

    if os.path.exists(spacebar_file):
        with open(spacebar_file, 'r') as f:
            content = f.read()
        content = re.sub(
            r'^export SPACEBAR_BOT_TOKEN\s*=\s*\S+.*$',
            f'export SPACEBAR_BOT_TOKEN={token}',
            content,
            flags=re.MULTILINE
        )
        with open(spacebar_file, 'w') as f:
            f.write(content)

print(f"Fixed {fixed} profiles with correct tokens")
if missing:
    print(f"WARNING: Profiles missing .env: {', '.join(missing)}")

# Verify uniqueness (compare middle of JWT, not the header)
seen = {}
dupes = 0
for name, token in token_map.items():
    env_file = os.path.join(PROFILES_DIR, name, '.env')
    if os.path.exists(env_file):
        with open(env_file) as f:
            content = f.read()
        m = re.search(r'DISCORD_BOT_TOKEN\s*=\s*(\S+)', content)
        if m:
            mid = m.group(1).strip()[30:60]  # skip JWT header
            if mid in seen:
                print(f"  REAL DUPE: {name} == {seen[mid]}")
                dupes += 1
            else:
                seen[mid] = name

print(f"Unique tokens (checked middle 30 chars): {len(seen)}")
if dupes:
    print(f"WARNING: {dupes} duplicate tokens found! Regenerate on VPS.")
